eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    instance-id: feign-consumer-8010
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
logging:
  level:
    root: INFO
management:
  endpoint:
    health:
      show-details: always
org:
  springframework:
    cloud:
      sleuth: DEBUG
server:
  port: 8010
spring:
  application:
    name: feign-consumer
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
