spring:
  application:
    name: feign-provider
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
logging:
  level:
    root: INFO
org:
  springframework:
    cloud:
      sleuth: DEBUG

