logging:
  level:
    root: INFO
management:
  endpoint:
    health:
      show-details: always
org:
  springframework:
    cloud:
      sleuth: DEBUG
spring:
  application:
    name: feign-consumer
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
