server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://192.168.2.17:3306/billionfun-order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useInformationSchema=false
    username: root
    password: zhuyi
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
  cloud:
    alibaba:
      seata:
        tx-service-group: prex_tx_group
    nacos:
      discovery:
        server-addr: 192.168.2.17:8848
          #group: pay
          #namespace: 8b038ac3-f97b-46e4-8e77-c10eff1aec5c
          #group: pay
          #cluster-name: BJ
          #metadata:
        #version: v1
    sentinel:
      transport:
        dashboard: 192.168.2.17:8858
  application:
    name: order-center
  redis:
    host: 192.168.2.17
    port: 6379
    database: 3
logging:
  level:
    com:
      billionfun:
        feignapi: debug
feign:
  client:
    config:
      order-center:
        loggerLevel: full
        contract: feign.Contract.Default
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'



