eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    instance-id: feign-provider-8002
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
logging:
  level:
    root: INFO
org:
  springframework:
    cloud:
      sleuth: DEBUG
server:
  port: 8002
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
